import snakebids
from snakebids import bids

configfile: 'config/config_preproc.yml'

sites = config['sites']
subjects = dict()

#read in txt file for each site
for site in sites:
    in_txt = config['subject_list'].format(site=site)
    with open(in_txt,'r') as f:
        subjects[site] = [s.replace('\n','') for s in f.readlines()]



app_config = config['apps']
apps = config['apps_to_run']
app_tmp = config['global_app_opts']['tmp']


rule all_preproc:
    input:
        expand('preproc/site-{site}/{app}/dataset_description.json',site=config['sites'],app=apps)


include: 'rules/preproc.smk'


