sites:
  - LHS
  - TWH
  - HSC


subject_list: 'config/subjects_{site}.txt' #this is a curated list that only has subjects with resting-state and T1w

bids_dir:
  HSC: '../eplink-spred2bids/bids/site-HSC'
  LHS: '../eplink-spred2bids/bids/site-LHS'
  TWH: '../eplink-spred2bids/bids/site-TWH'

global_app_opts:
  #tmp: '/tmp'
  tmp: '$SLURM_TMPDIR'


apps_to_run:
  - fmriprep_20.2.6
  - hippunfold

apps:

  hippunfold:
    command:
      - 'singularity run -e resources/singularity/hippunfold_latest.sif'
    opts: 
      - '--modality T1w'
    rsync_maps: #key can be any glob, but the destination (value) should be a folder, since it will be explicitly created with mkdir
      'results/sub-{subject}/': 'sub-{subject}' #watch out for trailing slash on the origin folder, it is required here.. 
      'work/sub-{subject}_*': 'sub-{subject}/work' 
    outputs:
      dirs:
        - 'sub-{subject}' 
    resources:
      mem_mb: 32000
      time: 180
      app_type: snakemake
    threads: 8



  fmriprep_20.2.6:
    command:
      - 'singularity run -e resources/singularity/fmriprep_20.2.6.sif'
    opts: 
      - '--fs-no-reconall'
      - '--notrack'
      - '--output-layout bids'
      - '--output-spaces T1w MNI152NLin6Asym MNI152NLin2009cAsym'
      - '--use-plugin /project/6050199/akhanf/ext-bids/eplink_phase3/eplink-preproc/resources/fmriprep_multiproc_8c_32gb.yaml'
    rsync_maps:
      'sub-{subject}/': 'sub-{subject}'
      'sub-{subject}.html': ''
    outputs:
      files:
        - 'sub-{subject}.html'
      dirs:
        - 'sub-{subject}' 
    resources:
      mem_mb: 32000
      time: 360
      app_type: nipype
    threads: 8
   

containers:
  "fmriprep_20.2.6": 'docker://nipreps/fmriprep:20.2.6'
  "hippunfold_latest": 'docker://khanlab/hippunfold:latest'

